[colors.bright]
black = "#af9657"
blue = "#96b9e6"
cyan = "#e684eb"
green = "#6f99c9"
magenta = "#8cb1de"
# red = "#93b3dc"
red = "#ff0080"
white = "#62b6b0"
yellow = "#a3c1e7"

[colors.cursor]
cursor = "#ff89ff"
text = "#000000"

[colors.normal]
black = "#2b192b" # Used for shell_gpt highlights
blue = "#8000ff"
cyan = "#cc00cc"
green = "#ff33ff"
magenta = "#ff1aff"
red = "#ff0080"
white = "#ff4d44"
yellow = "#ff89ff"

[colors.primary]
# background = "#0a0d11"
background = "#0f1216"
foreground = "#ffabff"

[colors.selection]
background = "#2b192b"
text = "#eaeaea"
